FROM node:18-alpine as builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Build the SSR version (the exact script name may vary)
RUN npm run build

# Then the final stage:
FROM node:18-alpine as production
WORKDIR /app

# Copy the entire dist from builder
COPY --from=builder /app/dist/ ./dist/

COPY package*.json ./
RUN npm ci --omit=dev

ENV PORT=8080
EXPOSE 8080

# Make sure the path matches the file that was generated by SSR
CMD ["node", "dist/angular-blog-app/server/server.mjs"]
